In [1]:
import numpy as np

# List

In [4]:
a = np.array([1, 2, 3])
print(a)
a

[1 2 3]


array([1, 2, 3])

In [7]:
A = [1, 'b', 'c']
print("Type(A)    : ",type(A))
print("Type(A[0]) : ",type(A[0]))
print("Type(A[1]) : ",type(A[1]))

Type(A)    :  <class 'list'>
Type(A[0]) :  <class 'int'>
Type(A[1]) :  <class 'str'>


In [8]:
B = [10,20,30,40,50,60]

In [12]:
print("B[2]   :",B[2])
print("B[3:6] :",B[3:6])
print("\nType of B[3:6] : ",type(B[3:6]))

B[2]   : 30
B[3:6] : [40, 50, 60]

Type of B[3:6] :  <class 'list'>


In [13]:
BinB = [1, 2, 'c', [1, 3, 4]]

In [14]:
type(BinB[3])

list

In [16]:
BinB[3][1]

3

In [18]:
BinBinB = [[B,B],BinB,[B,BinB]]
BinBinB

[[[10, 20, 30, 40, 50, 60], [10, 20, 30, 40, 50, 60]],
 [1, 2, 'c', [1, 3, 4]],
 [[10, 20, 30, 40, 50, 60], [1, 2, 'c', [1, 3, 4]]]]

In [19]:
C = [[1,2,3,4], [3,[12,4,5,65],'c', 10], 'a']
C[1][1][3]+10

75

# Vector

(중요) Python에서의 Vector 

* 1-D vector
    - row vector만 표현 가능
* 2-D vector
    - row, column vector 모두 표현 가능
* 어떤 방식을 사용해야하는가?
* vector 또는 행렬에 적용하는 함수에 return 방식을 알고 있어야함!!

In [38]:
#2by3 Vector a
X1 = np.array([1,2,3])
X1

array([1, 2, 3])

In [50]:
X2 = np.array([[6,5,7],X1,[7,8,9]])
X2

array([[6, 5, 7],
       [1, 2, 3],
       [7, 8, 9]])

In [51]:
X3 = np.array([[[1.,2.,3.],[4.,5.,6.],[7.,8.,9.]],X2])
X3

array([[[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]],

       [[6., 5., 7.],
        [1., 2., 3.],
        [7., 8., 9.]]])

In [64]:
X4=np.array([[[[[[[[[[[[[[[1]]]]]]]]]]]]]]])

In [65]:

print("Array X1 : \n shape : ", X1.shape ,"\n", X1)
print("Dimension of X1 : ", X1.ndim)
print("type of X1 : ", type(X1), "with" ,X1.dtype)

print("\n\nArray X2 : \n shape : ", X2.shape ,"\n", X2)
print("Dimension of X2 : ", X2.ndim)
print("type of X2 : ", type(X2), "with" ,X2.dtype)

print("\n\nArray X3 : \n shape : ", X3.shape ,"\n", X3)
print("Dimension of X3 : ", X3.ndim)
print("type of X3 : ", type(X3), "with" ,X3.dtype)

print("\n\nArray X3 : \n shape : ", X4.shape ,"\n", X4)
print("Dimension of X3 : ", X4.ndim)
print("type of X3 : ", type(X4), "with" ,X4.dtype)

Array X1 : 
 shape :  (3,) 
 [1 2 3]
Dimension of X1 :  1
type of X1 :  <class 'numpy.ndarray'> with int32


Array X2 : 
 shape :  (3, 3) 
 [[6 5 7]
 [1 2 3]
 [7 8 9]]
Dimension of X2 :  2
type of X2 :  <class 'numpy.ndarray'> with int32


Array X3 : 
 shape :  (2, 3, 3) 
 [[[1. 2. 3.]
  [4. 5. 6.]
  [7. 8. 9.]]

 [[6. 5. 7.]
  [1. 2. 3.]
  [7. 8. 9.]]]
Dimension of X3 :  3
type of X3 :  <class 'numpy.ndarray'> with float64


Array X3 : 
 shape :  (1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1) 
 [[[[[[[[[[[[[[[1]]]]]]]]]]]]]]]
Dimension of X3 :  15
type of X3 :  <class 'numpy.ndarray'> with int32


## Transpose

In [72]:
X = np.array([[1., 2., 3.],[4., 5., 6.]])
print("X   : \n", X  ,"\nshape : ",X.shape)
print("X.T : \n", X.T,"\nshape : ",X.T.shape)

X   : 
 [[1. 2. 3.]
 [4. 5. 6.]] 
shape :  (2, 3)
X.T : 
 [[1. 4.]
 [2. 5.]
 [3. 6.]] 
shape :  (3, 2)


In [68]:
Xt = np.array([1,2,3])
print("Xt   : ",Xt)
print("Xt.T : ",Xt.T)

Xt   :  [1 2 3]
Xt.T :  [1 2 3]


## Reshape

In [87]:
X = np.random.randint(1,100,(3,8))
X

array([[78, 32, 51, 98, 15, 23, 56, 60],
       [67, 64, 97, 67, 11, 51, 56, 10],
       [38,  4, 86, 20, 13, 59, 98, 13]])

In [88]:
X.reshape(2,12)

array([[78, 32, 51, 98, 15, 23, 56, 60, 67, 64, 97, 67],
       [11, 51, 56, 10, 38,  4, 86, 20, 13, 59, 98, 13]])

In [90]:
X.reshape(6,-1)

array([[78, 32, 51, 98],
       [15, 23, 56, 60],
       [67, 64, 97, 67],
       [11, 51, 56, 10],
       [38,  4, 86, 20],
       [13, 59, 98, 13]])

reshape 사용시 1차원 배열에 전치 안되는거 해결 가능.

In [97]:
X1dim = np.array([1,2,3])
print("X1dim   : \n", X1dim)
print("\nX1dim.T : \n", X1dim.T)
print("\nReshape : \n", X1dim.reshape(-1,1))

X1dim   : 
 [1 2 3]

X1dim.T : 
 [1 2 3]

Reshape : 
 [[1]
 [2]
 [3]]


* 다음 두개의 $x^{(i)}\in\mathbb{R}^3$ vector를 고려합시다:
\begin{align*}
x^{(1)} = \begin{bmatrix}
5\\
6\\
8
\end{bmatrix}, \quad
x^{(2)} = \begin{bmatrix}
6\\
7\\
5
\end{bmatrix}
\end{align*}

In [100]:
x1 = np.array([[5], [6], [7]])
x2 = np.array([[6], [7], [5]])
print('x1 : \n', x1)
print('x2 : \n', x2)

x1 : 
 [[5]
 [6]
 [7]]
x2 : 
 [[6]
 [7]
 [5]]


## Vstack and Hstack

* $X$ 행렬의 각 row (행)을 $(x^{(i)})^T\in \mathbb{R}^{1\times 3}$이라고 하겠습니다. 즉, 
\begin{align*}
X = \begin{bmatrix}
(x^{(1)})^T \\
(x^{(2)})^T \\
\end{bmatrix}
\end{align*}
과 같이 표현 됩니다. 

In [101]:
x1T = x1.T
x2T = x2.T
print('x1T : ', x1T)
print('x2T : ', x2T)

x1T :  [[5 6 7]]
x2T :  [[6 7 5]]


In [102]:
X = np.vstack([x1.T, x2.T])

* 즉 $X\in \mathbb{R}^{2\times 3}$ 는 다음과 같죠:
\begin{align*}
X = \begin{bmatrix}
5 & 6 & 8 \\
6 & 7 & 4 \\
\end{bmatrix}
\end{align*}

In [103]:
X

array([[5, 6, 7],
       [6, 7, 5]])

In [108]:
Xh = np.hstack([x1, x2])
XhT = Xh.T
XhT

array([[5, 6, 7],
       [6, 7, 5]])

# Array 생성 Tip

In [109]:
zvec = np.zeros((1,3))
zvec

array([[0., 0., 0.]])

In [110]:
ovec = np.ones((1,3))
ovec

array([[1., 1., 1.]])

In [118]:
np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [117]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

for문 돌릴때 유용

In [114]:
np.linspace(0,4,2)

array([0., 4.])

squeeze는 차원 축소할때 유용.

In [120]:
tra = np.array([[[[[[[[[[[[[[[[[1,2,3],[3,2,1]]]]]]]]]]]]]]]]])
tra

array([[[[[[[[[[[[[[[[[1, 2, 3],
                      [3, 2, 1]]]]]]]]]]]]]]]]])

In [122]:
sqtra = tra.squeeze()
sqtra

array([[1, 2, 3],
       [3, 2, 1]])

In [123]:
np.linspace(0,4,2)

array([0., 4.])

## Random

In [126]:
#랜덤
d = 2*np.random.rand(1,10)-1
d

array([[ 0.93890769,  0.8277666 , -0.01610096,  0.06553582,  0.15980802,
         0.74646538, -0.85713383, -0.38915737,  0.47950255, -0.77087182]])

In [127]:
#가우시안 분포로 뽑기
e = 2*np.random.randn(3,4)+2
e

array([[2.69042574, 0.29703581, 2.87454523, 5.29988149],
       [3.82144746, 4.13032006, 1.50243267, 1.96421948],
       [1.34991094, 2.27002926, 0.86646009, 2.41728885]])

# Matrix Operations

In [128]:
A = np.arange(0,6).reshape(3,2)
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [129]:
B = np.random.randn(3,4)
B

array([[-0.58035575, -0.47807078,  0.95527953,  0.42256984],
       [ 1.0226342 , -0.4236221 , -0.57606724,  0.3548313 ],
       [-0.67673057,  0.71130863, -0.31224859,  1.02147213]])

In [131]:
#(3,2) 와 (3,4) 덧셈... 오류
A + B

ValueError: operands could not be broadcast together with shapes (3,2) (3,4) 

In [136]:
AA = np.hstack([A,A])

In [137]:
AA + B

array([[-0.58035575,  0.52192922,  0.95527953,  1.42256984],
       [ 3.0226342 ,  2.5763779 ,  1.42393276,  3.3548313 ],
       [ 3.32326943,  5.71130863,  3.68775141,  6.02147213]])

In [145]:
np.matmul(B, AA.T)

array([[-0.05550094,  0.58334475,  1.22219043],
       [-0.0687908 ,  0.68676152,  1.44231384],
       [ 1.73278076,  3.22038396,  4.70798715]])

In [146]:
B @ AA.T

array([[-0.05550094,  0.58334475,  1.22219043],
       [-0.0687908 ,  0.68676152,  1.44231384],
       [ 1.73278076,  3.22038396,  4.70798715]])

In [147]:
np.dot(B, AA.T)

array([[-0.05550094,  0.58334475,  1.22219043],
       [-0.0687908 ,  0.68676152,  1.44231384],
       [ 1.73278076,  3.22038396,  4.70798715]])

단, 위의 matmul 과 dot, @는 2차원에서만 통용... 3차원부터는 결과 달라짐 교수님은 matmul선호,
저번학기에 3개 비교해서 속도 측정했던적 있었는데 @이 가장 빨랐던걸로 기억

In [148]:
a = np.linspace(0,6,4)
b = np.ones((4,1))

In [149]:
np.matmul(a,b)

array([12.])

이때 반환은 Scalar가 아니라 array로 돌려줌. 중요. dot, @ 도 마찬가지

In [150]:
a = np.linspace(0,6,4).reshape(1,4)
b = np.ones((4,1))

In [151]:
np.matmul(a,b)

array([[12.]])

차원을 유지하면서 나오는것에 유의

In [152]:
#숫자만 뽑아쓰기
np.matmul(a,b)[0][0]

12.0

* Matrix multiplication
    - `matmul`
    - Generate $A\in\mathbb{R}^{3\times 2}$, $a^{(i)}\in\mathbb{R}^{3}$
        \begin{align*}
            A = \begin{bmatrix}
                a^{(1)} & a^{(2)}  
            \end{bmatrix}
        \end{align*}
        - Example, 
            \begin{align*}
            a^{(1)} = \begin{bmatrix}
                3 \\
                4 \\
                5 \\
            \end{bmatrix}
        \end{align*}
    - Generate $B\in\mathbb{R}^{3\times 4}$
        \begin{align*}
            B = \begin{bmatrix}
                b^{(1)} & b^{(2)} & b^{(3)}  & b^{(4)}  
            \end{bmatrix}
        \end{align*}
    - $(a^{(1)})^T \cdot b^{(2)}$

Generate $A\in\mathbb{R}^{3\times 2}$, $a^{(i)}\in\mathbb{R}^{3}$

In [174]:
#Generate A
A = np.random.randint(0,10,(3,2))
A

array([[7, 4],
       [1, 6],
       [1, 3]])

\begin{align*}
            a^{(1)} = \begin{bmatrix}
                3 \\
                4 \\
                5 \\
            \end{bmatrix}
        \end{align*}

In [175]:
A[:,0]

array([7, 1, 1])

슬라이스 하면 차원 축소해서 반환함... 이거 Colunm Vector 아님 => reshape 사용

In [179]:
a1 = A[:,0].reshape(3,1)
a1

array([[7],
       [1],
       [1]])

Generate $B\in\mathbb{R}^{3\times 4}$
        \begin{align*}
            B = \begin{bmatrix}
                b^{(1)} & b^{(2)} & b^{(3)}  & b^{(4)}  
            \end{bmatrix}
        \end{align*}

In [176]:
B = np.random.randint(0,10,(3,4))
B

array([[8, 1, 5, 6],
       [0, 9, 5, 9],
       [6, 6, 1, 9]])

In [181]:
b2 = B[:,1].reshape(3,1)
b2

array([[1],
       [9],
       [6]])

$(a^{(1)})^T \cdot b^{(2)}$

In [184]:
np.matmul(a1.T,b2)[0,0]

22

In [187]:
#sum... 그냥 더하면 됨
C = np.random.randn(3,3)
D = np.random.randn(3,3)

C + D

array([[ 0.80664805, -1.14078916,  0.15014491],
       [ 0.09860738,  2.23648856, -0.90093456],
       [-2.37400912, -0.15073245, -0.38793912]])

In [188]:
a = np.array([1,2,3,4])
b = 2*np.ones(4)

In [191]:
#a와b를 원소별로 곱하고 싶을 때?
c = a*b
# * 는 행렬 곱과는 다르다.
c

array([2., 4., 6., 8.])

In [194]:
#sum 은 배열 내의 원소를 더한다... 1D 에선 내적
np.sum(a*b)

20.0

In [195]:
A = np.arange(3,11, 1).reshape(2,4)
A

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [197]:
#A 를 column별로 더하고 싶을때는?
np.sum(A, axis = 0)

array([10, 12, 14, 16])

In [201]:
#Row면
np.sum(A, axis = 1).reshape(-1,1)

array([[18],
       [34]])

## Broadcasting

In [208]:
A = np.random.randint(1,10,(4,3))
A

array([[8, 1, 4],
       [5, 2, 5],
       [3, 6, 9],
       [3, 2, 2]])

In [209]:
B= np.ones((4,1))
B

array([[1.],
       [1.],
       [1.],
       [1.]])

4by3행렬과 4by1행렬을 더한다? 당연히 오류가 날것이라 생각하지만 알아서 맞춰줌. => 브로드캐스팅

In [210]:
A+B

array([[ 9.,  2.,  5.],
       [ 6.,  3.,  6.],
       [ 4.,  7., 10.],
       [ 4.,  3.,  3.]])

* 참고

![This is the caption\label{mylabel}](https://scipy-lectures.org/_images/numpy_broadcasting.png)
https://scipy-lectures.org/_images/numpy_broadcasting.png

곱하기도 가능

In [213]:
B2 = B*2

In [214]:
A * B2

array([[16.,  2.,  8.],
       [10.,  4., 10.],
       [ 6., 12., 18.],
       [ 6.,  4.,  4.]])

+ For문 안쓰는 이유도 지난학기 직접 돌려보니 80배 이상 빠랐던걸로 기억함